[window]
startup_mode = "Maximized"
decorations = "Buttonless"
opacity = 1.0
blur = false
option_as_alt = "Both"

[font]
normal = { family = "NotoSansM Nerd Font", style = "Regular" }
size = 20.0

[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search.matches]
foreground = "#ffffff"
background = "#262626"

[colors.footer_bar]
foreground = "#ffffff"
background = "#262626"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
