[env]
TERM = "alacritty"

[window]
opacity = 1.0
startup_mode = "Maximized"
decorations = "Buttonless"
padding = { x = 10, y = 10 }
blur = false
option_as_alt = "Both"


[font]
normal = { family = "NotoSansM Nerd Font", style = "Regular" }
size = 18.0

[colors.primary]
background = "#272b30"
foreground = "#afb4c3"

[colors.normal]
black = "#272b30"
red = "#cc6666"
green = "#bdb968"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b08cba"
cyan = "#7fb2c8"
white = "#afb4c3"
