theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
popup-border = "all"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
