theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
auto-format = false
auto-pairs = false

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false