theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-format = false
completion-trigger-len = 1

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"